# Use a Node.js base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app/frontend

# Copy package.json to the container
# COPY package.json .
# COPY package-lock.json .
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 5173

# Command to run your application
CMD npm run dev



